var fen = require('../index');
var h = require('../lib/help');
var t = require('tape');
t('testTakeBack',function(test) {
  test.plan(6);
  var game = new fen();
  game.mm('e2e4');
  var hist = game.getHistory();
  test.equals(hist.length,2);
  game.takeBack();
  hist = game.getHistory();
  test.equals(hist.length,1);
  game.mm('g1f3');
  test.equals(game.getActivePlayer(),'black');
  game.mm('d7d6');
  test.equals(game.getActivePlayer(),'white');
  game.takeBack();
  test.equals(game.getActivePlayer(),'black');
  hist = game.getHistory();
  var last = hist.pop();
  test.equals(last.move,'g1f3');
 });